added commands: tambahkelas, listkelas
mhdfadlyhasan/Gijinka-bot-JS pull request #5
Opened 2020-09-30 14:40 UTC by Izzud

`npm install lodash --save`
add 2 commands

2020-09-30 23:54 UTC, mhdfadlyhasan commented on utilities/Kelas.js
> +                    let minutesRemaining = (menit_kelas > 0 ? 60 : menit_kelas) - date.getMinutes()
bukannya
(menit_kelas > 0 ?  menit_kelas : 60 )

2020-09-30 23:58 UTC, mhdfadlyhasan requested changes

2020-09-30 23:58 UTC, mhdfadlyhasan commented on utilities/Kelas.js
> +                    let minutesRemaining = (menit_kelas > 0 ? 60 : menit_kelas) - date.getMinutes()
ubah jadi
(menit_kelas > 0 ? menit_kelas : 60 )

2020-10-01 00:37 UTC, Izzud commented on utilities/Kelas.js
> +                    let minutesRemaining = (menit_kelas > 0 ? 60 : menit_kelas) - date.getMinutes()
welp, aku copas yg di discord

2020-10-01 00:50 UTC, merged